provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1
    lambdaHashingVersion: '20201221'

service: realtime-chat-app
useDotenv: true

plugins:
    - serverless-offline
    - serverless-webpack

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

functions:
    - ${file(src/functions/serverless.yml)}
