provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1
    lambdaHashingVersion: '20201221'

service: chatapp
useDotenv: true

plugins:
    - serverless-offline
    - serverless-webpack

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

functions:
    - ${file(src/functions/serverless.yml)}

resources:
    - ${file(resources/roles.yml)}
    - ${file(resources/policies.yml)}
    - ${file(resources/dynamodb.yml)}
    - ${file(resources/cognito.yml)}
    - ${file(resources/cognito-identity-pool.yml)}
