Resources:
    ChatTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: pk
                  AttributeType: S
                - AttributeName: sk
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: sortKeyIndex
                  KeySchema:
                      - AttributeName: sk
                        KeyType: HASH
                      - AttributeName: pk
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: pk
                  KeyType: HASH
                - AttributeName: sk
                  KeyType: RANGE
            TableName: realtime-chat-table
