user:
    handler: ./src/functions/user/index.handle
    role: CognitoDataRole
    events:
        - http:
              path: user
              method: POST
              cors: true

        - http:
              path: user/{email}
              method: GET
              cors: true
              authorizer:
                  type: COGNITO_USER_POOLS
                  authorizerId:
                      Ref: ApiGatewayAuthorizer
    environment:
        USER_POOL_ID: !Ref CognitoUserPool

websocket-handler:
    handler: ./src/functions/websocket-handler/index.handle
    role: WebSocketDataRole
    events:
        - websocket:
              route: $connect
              routeResponseSelectionExpression: $default
        - websocket:
              route: $disconnect
              routeResponseSelectionExpression: $default
        - websocket:
              route: $default
              routeResponseSelectionExpression: $default
    environment:
        USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient
        USER_POOL_ID: !Ref CognitoUserPool
