user:
    handler: ./src/functions/user/index.handle
    role: CognitoDataRole
    events:
        - http:
              path: user
              method: POST
              cors: true

        - http:
              path: user/{email}
              method: GET
              cors: true
    environment:
        USER_POOL_ID: !Ref CognitoUserPool
