user:
    handler: ./src/functions/user/index.handle
    role: DataRole
    events:
        - http:
              path: user
              method: POST
              cors: true

        - http:
              path: user/{email}
              method: GET
              cors: true
